config/routes.rb
Arena::Application.routes.draw do
  resources :lutadores
  
  match 'lutador_randomico' => 'lutadores#gen', as: :gen

  root to: "lutadores#index"
  

end

app/models/lutador.rb
class Lutador < ActiveRecord::Base
  attr_accessible :ataque, :classe, :defesa, :idade, :imagem, :nome, :prototipo_id, :taxa_ataque, :taxa_defesa, :taxa_tecnica, :tecnica, :apelido, :prototipo
  belongs_to :prototipo
  
  def total
    ataque + defesa + tecnica
  end
  
  def self.novo_aleatorio(prototipo = Prototipo.where(classe: Prototipo::SERVANO).first , sexo = "r")
    sexo = ((rand(2) == 0) ? "f" : "m") if (sexo == "r")
    Lutador.new do |l|
      l.prototipo = prototipo
      l.classe = prototipo.classe
      l.nome, l.apelido = Nome.randomico prototipo, sexo
      l.imagem = Retrato.randomico prototipo, sexo
      l.idade = prototipo.idade_minima + rand(5)
      l.ataque = prototipo.ataque + rand(10)
      l.defesa = prototipo.defesa + rand(10)
      l.tecnica = prototipo.tecnica + rand(10)
      l.taxa_ataque = prototipo.taxa_ataque + rand(3)
      l.taxa_defesa = prototipo.taxa_defesa + rand(3)
      l.taxa_tecnica = prototipo.taxa_tecnica + rand(3)
    end
  end  
  
end

app/models/nome.rb
class Nome < ActiveRecord::Base
  attr_accessible :palavra, :prototipo_id, :tipo, :prototipo, :genero
  belongs_to :prototipo
  
  validates :palavra, :tipo, presence: true
  
  MASCULINO = "m"
  FEMININO = "f"
  SOBRENOME = "sobrenome"
  APELIDO_MASCULINO = "apelido_masculino"
  APELIDO_FEMININO = "apelido_feminino"
  ADJETIVO = "adjetivo"
  GENERO_M = "m"
  GENERO_F = "f"
  GENERO_U = "u"
  
  TIPOS = [MASCULINO, FEMININO, SOBRENOME, APELIDO_MASCULINO, APELIDO_FEMININO, ADJETIVO]
  GENEROS = [GENERO_M, GENERO_F, GENERO_U]
  
  
  
  def self.randomico(prototipo = Prototipo.where(classe: Prototipo::SERVANO).first, sexo = self::GENERO_M)
    conjunto = Nome.where(prototipo_id: prototipo)
    if (sexo == Nome::MASCULINO) 
      primeiros = conjunto.where(tipo: Nome::MASCULINO)
      apelidos =  conjunto.where(tipo: Nome::APELIDO_MASCULINO)
    else
      primeiros = conjunto.where(tipo: Nome::FEMININO)
      apelidos =  conjunto.where(tipo: Nome::APELIDO_FEMININO)
    end 
    sobrenomes = conjunto.where(tipo: Nome::SOBRENOME)
    sobrenome = sobrenomes.first(offset: rand(sobrenomes.count)).palavra
    primeiro = primeiros.first(offset: rand(primeiros.count)).palavra
    apelido = apelidos.first(offset: rand(apelidos.count))
    if (apelido.genero.present? and !(rand(8) == 0))
      adjetivos = conjunto.where(tipo: Nome::ADJETIVO, genero: ["u", apelido.genero])
      adjetivo = adjetivos.first(offset: rand(adjetivos.count))
      apelido = "#{apelido.palavra} #{adjetivo.palavra}"
    else
      apelido = apelido.palavra  
    end
    ["#{primeiro} #{sobrenome}" , apelido]
  end
  
  
  
end

app/models/prototipo.rb
#!/bin/env ruby
# encoding: utf-8

class Prototipo < ActiveRecord::Base
  attr_accessible :classe, :ataque, :defesa, :idade_minima, :longevidade, :imagem, :taxa_ataque, :taxa_defesa, :taxa_tecnica, :tecnica
  has_many :lutadores
  has_many :nomes
  has_many :retratos
  
  SERVANO, ELFO, NEFANO, ORC, NIHONANO, BRUTO, BARBARO, ARCANO, DEMONIO, SELVAGEM, FOTONOIDE, DEMONOIDE, ESPARTANO, SINOANO, FELINO = 
  ["Servano", "Elfo", "Nefano", "Orc", "Nihonano", "Bruto", "Bárbaro", "Arcano", "Demônio", "Selvagem", "Fotonóide", "Demonóide", "Espartano", "Sinoano", "Felino"] 
  
  CLASSES = [SERVANO, ELFO, NEFANO, ORC, NIHONANO, BRUTO, BARBARO, ARCANO, DEMONIO, SELVAGEM, FOTONOIDE, DEMONOIDE, ESPARTANO, SINOANO, FELINO]
  
end

app/models/retrato.rb
class Retrato < ActiveRecord::Base
  attr_accessible :imagem, :prototipo_id, :sexo, :prototipo
  belongs_to :prototipo
  
  #TODO: corrigir sexos para m,f
  MASCULINO = "m"
  FEMININO = "f"
  
  def self.randomico(prototipo = Prototipo.where(classe: Prototipo::SERVANO).first, sexo = MASCULINO)
      retratos = where sexo: sexo, prototipo_id: prototipo
      retratos.first(offset: rand(retratos.count)).imagem
  end
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lutadores_controller.rb
class LutadoresController < ApplicationController
  # GET /lutadores
  # GET /lutadores.json
  def index
    @lutadores = (Lutador.count > 24) ? Lutador.all(limit: 24, offset: rand(Lutador.count - 24)) : Lutador.all
    @lutadores.reverse!
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lutadores }
    end
  end

  # GET /lutadores/1
  # GET /lutadores/1.json
  def show
    @lutador = Lutador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lutador }
    end
  end

  # GET /lutadores/new
  # GET /lutadores/new.json
  def new
    @lutador = Lutador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lutador }
    end
  end

  # GET /lutadores/1/edit
  def edit
    @lutador = Lutador.find(params[:id])
  end

  # POST /lutadores
  # POST /lutadores.json
  def create
    @lutador = Lutador.new(params[:lutador])

    respond_to do |format|
      if @lutador.save
        format.html { redirect_to @lutador, notice: 'Lutador was successfully created.' }
        format.json { render json: @lutador, status: :created, location: @lutador }
      else
        format.html { render action: "new" }
        format.json { render json: @lutador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lutadores/1
  # PUT /lutadores/1.json
  def update
    @lutador = Lutador.find(params[:id])

    respond_to do |format|
      if @lutador.update_attributes(params[:lutador])
        format.html { redirect_to @lutador, notice: 'Lutador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lutador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lutadores/1
  # DELETE /lutadores/1.json
  def destroy
    @lutador = Lutador.find(params[:id])
    @lutador.destroy

    respond_to do |format|
      format.html { redirect_to lutadores_url }
      format.json { head :no_content }
    end
  end
  
  def gen
    Lutador.novo_aleatorio.save
    redirect_to lutadores_path
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lutadores_helper.rb
#!/bin/env ruby
# encoding: utf-8

module LutadoresHelper


def label_taxa(taxa)
  if (taxa % 2) == 1
    t = taxa + 1 
  else
    t = taxa
  end
  content_tag(:span, "+ #{taxa}", class: "label label#{t}")
end

def atributos(lutador)
  idade = content_tag(:td, "Idade") + content_tag(:td, lutador.idade) + content_tag(:td, link_to("Remover", lutador, method: :delete, class: "btn btn-danger btn-mini"))
  ataque = content_tag(:td, "Ataque") + content_tag(:td, lutador.ataque) + content_tag(:td, label_taxa(lutador.taxa_ataque))
  defesa = content_tag(:td, "Defesa") + content_tag(:td, lutador.defesa) + content_tag(:td, label_taxa(lutador.taxa_defesa))
  tecnica = content_tag(:td, "Técnica") + content_tag(:td, lutador.tecnica) + content_tag(:td, label_taxa(lutador.taxa_tecnica))
  tbody = content_tag(:tbody, content_tag(:tr, idade) + content_tag(:tr, ataque) + content_tag(:tr, defesa) + content_tag(:tr, tecnica))
  content_tag :table, tbody, class: "table table-condensed table-striped"
end



end

app/views/application/_navbar.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid topbar">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!--<a class="brand" href="#">Arena</a>-->
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to image_tag("icones/globo.png", size: "64x64"), "#"  %></li>
              <li><%= link_to image_tag("icones/luva.png", size: "64x64"), "/lutadores"  %></li>
              <li><%= link_to image_tag("icones/estrutura.png", size: "64x64"), "#"  %></li>
              <li><%= link_to image_tag("icones/binoculos.png", size: "64x64"), "#"  %></li>
              <li><%= link_to image_tag("icones/muro.png", size: "64x64"), "#"  %></li>
              <li><%= link_to image_tag("icones/cone.png", size: "64x64"), "#"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Arena" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <%= render "navbar" %>

    <div class="container-fluid corpo">
      <%= yield %>
    </div> <!-- /container -->

      <footer>
        <p>alexandre.abreu.uff@gmail.com</p>
      </footer>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/lutadores/_form.html.erb
<%= form_for @lutador, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :prototipo_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :prototipo_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :imagem, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imagem, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :classe, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :classe, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :idade, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :idade, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ataque, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :ataque, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :defesa, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :defesa, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tecnica, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :tecnica, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :taxa_ataque, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :taxa_ataque, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :taxa_defesa, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :taxa_defesa, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :taxa_tecnica, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :taxa_tecnica, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lutadores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lutadores/edit.html.erb
<%- model_class = @lutador.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lutadores/index.html.erb
<% cont = 1 %>
<% aberto = true %>
<div class="row-fluid">
	<div class="span2 display-lutador">
		<div class="inner-lutador adicionador">
			<%= link_to image_tag("icones/+.png"), gen_path %>
		</div>
	</div>
<% @lutadores.each do |lutador| %>
<% if (cont % 6) == 0  %>
	<% if (aberto) %>
		</div>
	<% end %>
	<div class="row-fluid">
	<% aberto = true %>
<% end %>

<div class="span2 display-lutador">
	<div class="inner-lutador">
		<div class="row-fluid">
			<%= image_tag lutador.imagem, size: "100x100" %>
			<div class="total-lutador"><%= lutador.total %></div>
		</div>
		<h3 class="nome-lutador"><%= lutador.nome %></h3>
		<h3 class="nome-lutador"><%= lutador.apelido %></h3>
		<%= atributos(lutador)%>
	</div>
</div>
 <% cont += 1 %>
<% end %>

<% if (aberto) %>
		</div>
	<% end %>

	

app/views/lutadores/new.html.erb
<%- model_class = @lutador.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lutadores/show.html.erb
<%- model_class = @lutador.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:prototipo_id) %>:</strong></dt>
  <dd><%= @lutador.prototipo_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imagem) %>:</strong></dt>
  <dd><%= @lutador.imagem %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @lutador.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @lutador.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:classe) %>:</strong></dt>
  <dd><%= @lutador.classe %></dd>
  <dt><strong><%= model_class.human_attribute_name(:idade) %>:</strong></dt>
  <dd><%= @lutador.idade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ataque) %>:</strong></dt>
  <dd><%= @lutador.ataque %></dd>
  <dt><strong><%= model_class.human_attribute_name(:defesa) %>:</strong></dt>
  <dd><%= @lutador.defesa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tecnica) %>:</strong></dt>
  <dd><%= @lutador.tecnica %></dd>
  <dt><strong><%= model_class.human_attribute_name(:taxa_ataque) %>:</strong></dt>
  <dd><%= @lutador.taxa_ataque %></dd>
  <dt><strong><%= model_class.human_attribute_name(:taxa_defesa) %>:</strong></dt>
  <dd><%= @lutador.taxa_defesa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:taxa_tecnica) %>:</strong></dt>
  <dd><%= @lutador.taxa_tecnica %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lutadores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lutador_path(@lutador), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lutador_path(@lutador),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>